package analyze

import (
	"archive/zip"
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"path/filepath"
	"sort"
	"strings"
)

// ReproZipFileInspection describes one file found inside a minimal reproduction
// package. Hashes are included so a package can be compared without extracting
// it first.
type ReproZipFileInspection struct {
	Path        string `json:"path"`
	Bytes       int64  `json:"bytes"`
	SHA256      string `json:"sha256"`
	Required    bool   `json:"required"`
	Description string `json:"description,omitempty"`
}

// ReproZipCheck is a small, CI-friendly validation row. Status is pass, warn,
// fail, or info.
type ReproZipCheck struct {
	Name   string `json:"name"`
	Status string `json:"status"`
	Detail string `json:"detail,omitempty"`
	Hint   string `json:"hint,omitempty"`
}

// ReproZipInspection is the result of validating a minimal reproduction ZIP
// generated by rvsmoke -repro-zip. It deliberately avoids extracting files to
// disk and flags unsafe paths before any caller writes them.
type ReproZipInspection struct {
	Status         string                   `json:"status"`
	ZipSHA256      string                   `json:"zip_sha256,omitempty"`
	Files          []ReproZipFileInspection `json:"files,omitempty"`
	Missing        []string                 `json:"missing,omitempty"`
	Unexpected     []string                 `json:"unexpected,omitempty"`
	Checks         []ReproZipCheck          `json:"checks,omitempty"`
	BundleSHA256   string                   `json:"bundle_sha256,omitempty"`
	ManifestSHA256 string                   `json:"manifest_sha256,omitempty"`
	ArtifactPins   []ArtifactIntegrityRow   `json:"artifact_pins,omitempty"`
	Summary        []string                 `json:"summary,omitempty"`
}

func requiredReproPackageFiles() map[string]string {
	spec := BuildMinimalReproPackageSpec(DiagnosticBundle{}, HeadlessSmokeRunnerSpec{})
	out := map[string]string{}
	for _, f := range spec.Files {
		out[f.Path] = f.Description
	}
	// These are currently generated by MinimalReproPackageFiles as well; keep
	// them required so package handoff remains self-contained.
	out["policy-violation-tree.md"] = "policy violation explanation"
	out["history.txt"] = "bundle trend/history summary"
	return out
}

func InspectMinimalReproZipBytes(data []byte) (ReproZipInspection, error) {
	r := ReproZipInspection{ZipSHA256: shaBytes(data)}
	zr, err := zip.NewReader(bytes.NewReader(data), int64(len(data)))
	if err != nil {
		r.Status = "fail"
		r.Checks = append(r.Checks, ReproZipCheck{Name: "zip-open", Status: "fail", Detail: err.Error(), Hint: "verify the file is the rvsmoke minimal reproduction zip"})
		return r, err
	}
	required := requiredReproPackageFiles()
	seen := map[string]bool{}
	contents := map[string][]byte{}
	add := func(name, status, detail, hint string) {
		r.Checks = append(r.Checks, ReproZipCheck{Name: name, Status: status, Detail: detail, Hint: hint})
	}
	add("zip-open", "pass", fmt.Sprintf("%d file(s)", len(zr.File)), "")
	for _, f := range zr.File {
		name := filepath.ToSlash(f.Name)
		unsafe := strings.HasPrefix(name, "/") || strings.Contains(name, "../") || name == ".." || strings.HasPrefix(name, "..")
		if unsafe {
			add("path-safety:"+name, "fail", "unsafe zip path", "do not extract this package without rewriting paths")
		}
		if seen[name] {
			add("duplicate:"+name, "warn", "duplicate file path in zip", "regenerate the reproduction package")
		}
		seen[name] = true
		rc, err := f.Open()
		if err != nil {
			add("read:"+name, "fail", err.Error(), "regenerate the zip")
			continue
		}
		b, err := io.ReadAll(io.LimitReader(rc, 64<<20))
		_ = rc.Close()
		if err != nil {
			add("read:"+name, "fail", err.Error(), "regenerate the zip")
			continue
		}
		contents[name] = b
		_, req := required[name]
		r.Files = append(r.Files, ReproZipFileInspection{Path: name, Bytes: int64(len(b)), SHA256: shaBytes(b), Required: req, Description: required[name]})
		if !req && !strings.HasSuffix(name, "/") {
			r.Unexpected = append(r.Unexpected, name)
		}
	}
	sort.Slice(r.Files, func(i, j int) bool { return r.Files[i].Path < r.Files[j].Path })
	for p := range required {
		if !seen[p] {
			r.Missing = append(r.Missing, p)
		}
	}
	sort.Strings(r.Missing)
	sort.Strings(r.Unexpected)
	if len(r.Missing) == 0 {
		add("required-files", "pass", "all required reproduction files are present", "")
	} else {
		add("required-files", "fail", strings.Join(r.Missing, ", "), "regenerate with rvsmoke -repro-zip")
	}
	if len(r.Unexpected) != 0 {
		add("unexpected-files", "info", strings.Join(r.Unexpected, ", "), "unexpected files are ignored by rvsmoke but may be useful attachments")
	}

	var bundle DiagnosticBundle
	bundleOK := false
	if b, ok := contents["diagnostic-bundle.json"]; ok {
		parsed, raw, err := ParseDiagnosticBundleText(string(b))
		if err != nil {
			add("diagnostic-bundle", "fail", err.Error(), "replace diagnostic-bundle.json with an exported bundle")
		} else {
			bundle = parsed
			bundleOK = true
			r.BundleSHA256 = shaText(raw)
			add("diagnostic-bundle", "pass", "bundle parses", "")
		}
	}
	var manifest ArtifactManifest
	manifestOK := false
	if b, ok := contents["manifest.json"]; ok {
		if err := json.Unmarshal(b, &manifest); err != nil {
			add("manifest", "fail", err.Error(), "replace manifest.json with Artifact manifest JSON")
		} else {
			manifestOK = true
			r.ManifestSHA256 = shaText(ArtifactManifestJSON(manifest))
			add("manifest", "pass", "manifest parses", "")
		}
	}
	if bundleOK && manifestOK {
		want := shaText(ArtifactManifestJSON(bundle.Manifest))
		got := shaText(ArtifactManifestJSON(manifest))
		if want == got {
			add("manifest-vs-bundle", "pass", "manifest matches bundle manifest", "")
		} else {
			add("manifest-vs-bundle", "fail", "manifest.json differs from diagnostic-bundle manifest", "keep both files from the same rvsmoke run")
		}
		for _, a := range bundle.Manifest.Artifacts {
			r.ArtifactPins = append(r.ArtifactPins, ArtifactIntegrityRow{Role: a.Role, Bytes: a.Bytes, Range: fmt.Sprintf("%#x..%#x", a.LoadAddr, a.EndAddr), Entry: fmt.Sprintf("%#x", a.Entry), SHA256: shortHash(a.SHA256), LooksValid: looksLikeSHA256(a.SHA256)})
		}
		sort.Slice(r.ArtifactPins, func(i, j int) bool { return r.ArtifactPins[i].Role < r.ArtifactPins[j].Role })
	}
	if b, ok := contents["ci-policy.json"]; ok {
		if _, err := ParseCIGatePolicyJSON(string(b), DefaultCIGatePolicy()); err != nil {
			add("ci-policy", "warn", err.Error(), "regenerate ci-policy.json or use -policy-template")
		} else {
			add("ci-policy", "pass", "policy parses", "")
		}
	}
	if b, ok := contents["scripts/rvsmoke.sh"]; ok {
		text := string(b)
		switch {
		case !strings.Contains(text, "rvsmoke"):
			add("script", "warn", "scripts/rvsmoke.sh does not mention rvsmoke", "regenerate the package")
		case !strings.Contains(text, "diagnostic-bundle.json"):
			add("script", "warn", "script does not reference diagnostic-bundle.json", "regenerate the package")
		default:
			add("script", "pass", "rvsmoke script looks usable", "")
		}
	}
	r.Status = statusFromChecks(r.Checks)
	r.Summary = append(r.Summary, fmt.Sprintf("files=%d required_missing=%d unexpected=%d", len(r.Files), len(r.Missing), len(r.Unexpected)))
	if len(r.ArtifactPins) != 0 {
		r.Summary = append(r.Summary, fmt.Sprintf("artifact_pins=%d", len(r.ArtifactPins)))
	}
	return r, nil
}

func InspectMinimalReproZipString(r ReproZipInspection) string {
	var b strings.Builder
	fmt.Fprintf(&b, "minimal repro zip status=%s files=%d missing=%d unexpected=%d sha=%s\n", r.Status, len(r.Files), len(r.Missing), len(r.Unexpected), shortHash(r.ZipSHA256))
	for _, s := range r.Summary {
		fmt.Fprintf(&b, "  - %s\n", s)
	}
	if len(r.Missing) != 0 {
		b.WriteString("missing required files:\n")
		for _, m := range r.Missing {
			fmt.Fprintf(&b, "  - %s\n", m)
		}
	}
	if len(r.Files) != 0 {
		b.WriteString("files:\n")
		for _, f := range r.Files {
			mark := "optional"
			if f.Required {
				mark = "required"
			}
			fmt.Fprintf(&b, "  %-28s %-8s bytes=%-8d sha=%s\n", f.Path, mark, f.Bytes, shortHash(f.SHA256))
		}
	}
	if len(r.Checks) != 0 {
		b.WriteString("checks:\n")
		for _, c := range r.Checks {
			fmt.Fprintf(&b, "  %-5s %-24s %s\n", c.Status, c.Name, c.Detail)
			if c.Hint != "" {
				fmt.Fprintf(&b, "        hint: %s\n", c.Hint)
			}
		}
	}
	return b.String()
}

func InspectMinimalReproZipJSON(r ReproZipInspection) string {
	b, _ := json.MarshalIndent(r, "", "  ")
	return string(b)
}

// GitHubActionsMatrixWorkflowYAML emits a workflow where the rvsmoke invocation
// runs once per preset. It is intentionally generated as text instead of using a
// YAML library so users can paste it directly into .github/workflows/.
func GitHubActionsMatrixWorkflowYAML(policyTemplate string, presets []string) string {
	if strings.TrimSpace(policyTemplate) == "" {
		policyTemplate = "linux-boot"
	}
	if _, ok := CIGatePolicyTemplateByName(policyTemplate); !ok {
		policyTemplate = "default"
	}
	if len(presets) == 0 {
		presets = []string{"uart-blk", "hvc-blk", "uart-initrd", "hvc-initrd", "simplefb"}
	}
	quoted := make([]string, 0, len(presets))
	for _, p := range presets {
		p = strings.TrimSpace(p)
		if p != "" {
			quoted = append(quoted, fmt.Sprintf("'%s'", strings.ReplaceAll(p, "'", "")))
		}
	}
	if len(quoted) == 0 {
		quoted = []string{"'uart-blk'"}
	}
	return fmt.Sprintf(`name: rvwasm smoke matrix

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  rvsmoke:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        preset: [%s]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'

      - name: Build tools
        run: |
          go test ./...
          CGO_ENABLED=0 go build -trimpath -buildvcs=false -ldflags='-s -w' -o ./bin/rvsmoke ./cmd/rvsmoke

      - name: Run rvsmoke for ${{ matrix.preset }}
        run: |
          ./bin/rvsmoke \
            -bundle artifacts/rvwasm-diagnostic-bundle.json \
            -trace artifacts/trace-${{ matrix.preset }}.txt \
            -console artifacts/console-${{ matrix.preset }}.txt \
            -presets ${{ matrix.preset }} \
            -policy-template %s \
            -junit rvwasm-${{ matrix.preset }}.xml \
            -html rvwasm-${{ matrix.preset }}.html \
            -out md > rvwasm-${{ matrix.preset }}.md

      - name: Upload rvwasm reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rvwasm-${{ matrix.preset }}
          path: |
            rvwasm-${{ matrix.preset }}.md
            rvwasm-${{ matrix.preset }}.html
            rvwasm-${{ matrix.preset }}.xml
`, strings.Join(quoted, ", "), policyTemplate)
}

type TrendChartPoint struct {
	Index        int    `json:"index"`
	Name         string `json:"name"`
	Status       string `json:"status"`
	StatusScore  int    `json:"status_score"`
	DiffCount    int    `json:"diff_count"`
	ArtifactHash int    `json:"artifact_hash_count"`
	Phase        string `json:"phase,omitempty"`
	TopStopCause string `json:"top_stop_cause,omitempty"`
}

type BundleTrendChartData struct {
	Status string            `json:"status"`
	Points []TrendChartPoint `json:"points"`
	Notes  []string          `json:"notes,omitempty"`
}

func BuildBundleTrendChartData(trend BundleTrendReport) BundleTrendChartData {
	out := BundleTrendChartData{Status: firstNonEmpty(trend.Status, "empty")}
	diffByTo := map[string]int{}
	for _, d := range trend.Diffs {
		diffByTo[d.To]++
	}
	for _, r := range trend.Rows {
		out.Points = append(out.Points, TrendChartPoint{Index: r.Index, Name: r.Name, Status: r.Status, StatusScore: statusScore(r.Status), DiffCount: diffByTo[r.Name], ArtifactHash: len(r.Artifacts), Phase: r.Phase, TopStopCause: r.TopStopCause})
	}
	out.Notes = append(out.Notes, trend.Summary...)
	return out
}

func BundleTrendChartDataJSON(data BundleTrendChartData) string {
	b, _ := json.MarshalIndent(data, "", "  ")
	return string(b)
}

func BundleTrendCSV(trend BundleTrendReport) string {
	var b strings.Builder
	b.WriteString("index,name,status,phase,top_stop_cause,manifest_sha256,bundle_sha256,diff_count,artifact_roles\n")
	diffByTo := map[string]int{}
	for _, d := range trend.Diffs {
		diffByTo[d.To]++
	}
	for _, r := range trend.Rows {
		roles := make([]string, 0, len(r.Artifacts))
		for role := range r.Artifacts {
			roles = append(roles, role)
		}
		sort.Strings(roles)
		fmt.Fprintf(&b, "%d,%s,%s,%s,%s,%s,%s,%d,%s\n", r.Index, csvCell(r.Name), csvCell(r.Status), csvCell(r.Phase), csvCell(r.TopStopCause), csvCell(r.ManifestSHA256), csvCell(r.BundleSHA256), diffByTo[r.Name], csvCell(strings.Join(roles, ";")))
	}
	return b.String()
}

func shaBytes(data []byte) string {
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:])
}

func statusFromChecks(checks []ReproZipCheck) string {
	status := "pass"
	for _, c := range checks {
		switch c.Status {
		case "fail", "error":
			return "fail"
		case "warn", "warning":
			if status == "pass" {
				status = "warn"
			}
		}
	}
	return status
}

func statusScore(s string) int {
	switch strings.ToLower(strings.TrimSpace(s)) {
	case "pass", "ok":
		return 0
	case "warn", "warning":
		return 1
	case "fail", "error":
		return 2
	default:
		return -1
	}
}

func csvCell(s string) string {
	if strings.ContainsAny(s, ",\n\r\"") {
		return "\"" + strings.ReplaceAll(s, "\"", "\"\"") + "\""
	}
	return s
}
